package model.Player;

/**
 * Desc: Enum for what type a player is
 * Author: Christopher Banas
 */
public enum Type {THREE_AND_D, ALL_AROUND, OFFENSIVE_PLAYMAKER, DEFENSIVE_PLAYMAKER, PLAYMAKER,
    ENERGETIC_REBOUNDER, THREE_LEVEL_SCORER, POST_PLAYER, INSIDE_OUTSIDE_DEFENDER, PURE_SHOOTER, STRETCH_BIG,
    INSIDE_DEFENDER, PERIMETER_DEFENDER, PAINT_BEAST, OFFENSIVE_SUPERSTAR, POINT_GOD, BALANCED_SUPERSTAR,
    LOCKDOWN_DEFENDER, TWO_WAY_SUPERSTAR, GOD}


